version: "3"
services:
  app_proxy:
    environment:
      APP_HOST: beaver-freeciv_web_1
      APP_PORT: 8031
  freeciv-web:
    image: freeciv/freeciv-web
    build: ./
    container_name: fcw.org
    command: ["sleep", "infinity"]
    volumes:
      - "${APP_DATA_DIR}:/var/lib/tomcat8/webapps/data"
    ports:
      - "8031:80"
      - "4002"
      - "6000-6009:6000-6009"
      - "7000-7009:7000-7009"
      - "8888:8080"
    user: docker

volumes:
  data:
